name: Boost.Test

on:
  push:

jobs:
  ubuntu_bionic:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get install cmake libeigen3-dev libboost-all-dev -y
    - name: build and test
      run: |
        mkdir -p build
        cd build && cmake .. && make unit_test && ./unit_test

  ubuntu_focal:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
    - name: Install required packages
      run: sudo apt-get update && sudo apt-get install cmake libeigen3-dev libboost-all-dev -y
    - name: build and test
      run: |
        mkdir -p build
        cd build && cmake .. && make unit_test && ./unit_test

  macOS_Catalina:
    runs-on: macos-10.15
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
    - name: Install required packages
      run: brew install eigen boost
    - name: build and test
      run: |
        mkdir -p build
        cd build && cmake .. && make unit_test && ./unit_test
